# 389. Find the Difference

# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

from collections import Counter
class Solution:
    def __init__(self, s, t):
        self.s = s
        self.t = t
    
    def findTheDifference(self):
        # t = list(self.t)
        # for ch in self.s:
        #     if ch in t:
        #         t.remove(ch)
        # return str(t)
        count = Counter(self.t)
        for c in self.s:
            count[c] -= 1
            if count[c] == 0:
                del count[c]
        return list(count.keys())[0]

if __name__ == "__main__":
    diff_ch = Solution("", "y")
    print(diff_ch.findTheDifference())